[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onleash = "6ufLBSxNADjAAS7NT5f9Phnvjxc2We7n7q8s9uKx5GBn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
